[package]
name = "rust_wasm_examples"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.77"
web-sys = { version="0.3.77", features = ["console"] }